### ISSUE TITLE
关于日志文件无法自动删除问题

### ISSUE THREAD

**Issue by super963883929** [QiuYaohong/kuwoMusicApi#16]
这项目跑起来日志文件不会自动删除,跑了一晚上把我200多G的磁盘跑满了

**Comment by qyhqiu** [comment]
加了一个定时任务，自动删除logs

**Comment by super963883929** [comment]
最近好多接口都失效了,现在的版本是不是修复好了?

**Comment by qyhqiu** [comment]
> 最近好多接口都失效了,现在的版本是不是修复好了?

官网 接口加密了 Secret, 请求头多了一个 Secret 字段，加上去就好了， 现在所有的接口都可以请求了

定时任务删除日志 默认设置的 24h 删除一次， 你可以自己更改设置
文件地址: \app\schedule\logs.ts
const fse = require('fs-extra')
//  https://www.eggjs.org/zh-CN/basics/schedule#%E5%AE%9A%E6%97%B6%E6%96%B9%E5%BC%8F
module.exports = app => {
  return {
    schedule: {
      //  每 24 h 清除 logs
      interval: '86440s',
      type: 'all', // 指定所有的 worker 都需要执行
    },
    async task () {
      fse.emptydirSync(app.config?.logger?.dir, err => {
        if (!err) {
          return console.log('emptydirSync success')
        }
      })
    },
  }
}

**Comment by super963883929** [comment]
好的,还有一个我在本地用你最新的版本按照步骤到: `npm run start`以后就报: ` > kuwomusicapi@1.0.0 start
> egg-scripts start --daemon --port 7002 --title=egg-server-server-egg

[egg-scripts] Starting egg application at C:\Users\a\Desktop\test\kuwoMusicApi-master
[egg-scripts] Run node --no-deprecation --require C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\source-map-support\register.js C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-scripts\lib\start-cluster {"port":7002,"title":"egg-server-server-egg","baseDir":"C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master","framework":"C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg"} --title=egg-server-server-egg
[egg-scripts] Save log file to C:\Users\a\logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] Wait Start: 5...
[egg-scripts] Wait Start: 6...
[egg-scripts] Wait Start: 7...
[egg-scripts] Wait Start: 8...
[egg-scripts] Wait Start: 9...
[egg-scripts] Wait Start: 10...
[egg-scripts] Wait Start: 11...
[egg-scripts] tail -n 100 C:\Users\a\logs\master-stderr.log
[egg-scripts] Got error when startup:
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[egg-scripts] code: "MODULE_NOT_FOUND"
[egg-scripts] requireStack: ["C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\app\\service\\BaseService.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\app\\service\\albumInfo.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-core\\lib\\utils\\index.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-core\\lib\\egg.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-core\\index.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg\\lib\\application.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg\\index.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-cluster\\lib\\app_worker.js"]
[egg-scripts] name: "MODULE_NOT_FOUNDError"
[egg-scripts] pid: 17552
[egg-scripts] hostname: DESKTOP-2FLB9GC
[egg-scripts]
[egg-scripts] MODULE_NOT_FOUNDError: [egg-core] load file: C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\albumInfo.js, error: Cannot find module '../utils/secret'
[egg-scripts] Require stack:
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\BaseService.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\albumInfo.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\utils\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\egg.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\lib\application.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\app_worker.js
[egg-scripts]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[egg-scripts]     at require (node:internal/modules/cjs/helpers:102:18)
[egg-scripts]     at Object.<anonymous> (C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\BaseService.ts:4:1)
[egg-scripts]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[egg-scripts]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[egg-scripts]     at Module.load (node:internal/modules/cjs/loader:981:32)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[egg-scripts] 2023-07-22 15:12:25,152 ERROR 4400 nodejs.AppWorkerDiedError: [master] app_worker#4:16844 died (code: 1, signal: null, suicide: false, state: dead), current workers: ["1","2","3","5","6","7","8","9","10","11","12"]
[egg-scripts]     at Master.onAppExit (C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\master.js:510:21)
[egg-scripts]     at Master.emit (node:events:526:28)
[egg-scripts]     at Messenger.sendToMaster (C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\utils\messenger.js:137:17)
[egg-scripts]     at Messenger.send (C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\utils\messenger.js:102:12)
[egg-scripts]     at EventEmitter.<anonymous> (C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\master.js:353:22)
[egg-scripts]     at EventEmitter.emit (node:events:538:35)
[egg-scripts]     at ChildProcess.<anonymous> (node:internal/cluster/primary:203:13)
[egg-scripts]     at Object.onceWrapper (node:events:646:26)
[egg-scripts]     at ChildProcess.emit (node:events:526:28)
[egg-scripts]     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
[egg-scripts] name: "AppWorkerDiedError"
[egg-scripts] pid: 4400
[egg-scripts] hostname: DESKTOP-2FLB9GC
[egg-scripts]
[egg-scripts] 2023-07-22 15:12:25,152 ERROR 4400 [master] app_worker#4:16844 start fail, exiting with code:1
[egg-scripts] 2023-07-22 15:12:25,153 ERROR 4400 [master] exit with code:1
[egg-scripts] 2023-07-22 15:12:25,154 ERROR 18180 nodejs.MODULE_NOT_FOUNDError: [egg-core] load file: C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\albumInfo.js, error: Cannot find module '../utils/secret'
[egg-scripts] Require stack:
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\BaseService.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\albumInfo.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\utils\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\egg.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\lib\application.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\app_worker.js
[egg-scripts] Require stack:
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\BaseService.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\albumInfo.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\utils\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\egg.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\lib\application.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\app_worker.js
[egg-scripts]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[egg-scripts]     at require (node:internal/modules/cjs/helpers:102:18)
[egg-scripts]     at Object.<anonymous> (C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\BaseService.ts:4:1)
[egg-scripts]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[egg-scripts]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[egg-scripts]     at Module.load (node:internal/modules/cjs/loader:981:32)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[egg-scripts] code: "MODULE_NOT_FOUND"
[egg-scripts] requireStack: ["C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\app\\service\\BaseService.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\app\\service\\albumInfo.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-core\\lib\\utils\\index.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-core\\lib\\egg.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-core\\index.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg\\lib\\application.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg\\index.js","C:\\Users\\a\\Desktop\\test\\kuwoMusicApi-master\\node_modules\\egg-cluster\\lib\\app_worker.js"]
[egg-scripts] name: "MODULE_NOT_FOUNDError"
[egg-scripts] pid: 18180
[egg-scripts] hostname: DESKTOP-2FLB9GC
[egg-scripts]
[egg-scripts] MODULE_NOT_FOUNDError: [egg-core] load file: C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\albumInfo.js, error: Cannot find module '../utils/secret'
[egg-scripts] Require stack:
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\BaseService.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\albumInfo.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\utils\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\lib\egg.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-core\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\lib\application.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg\index.js
[egg-scripts] - C:\Users\a\Desktop\test\kuwoMusicApi-master\node_modules\egg-cluster\lib\app_worker.js
[egg-scripts]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[egg-scripts]     at require (node:internal/modules/cjs/helpers:102:18)
[egg-scripts]     at Object.<anonymous> (C:\Users\a\Desktop\test\kuwoMusicApi-master\app\service\BaseService.ts:4:1)
[egg-scripts]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[egg-scripts]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[egg-scripts]     at Module.load (node:internal/modules/cjs/loader:981:32)
[egg-scripts]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[egg-scripts]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[egg-scripts]
[egg-scripts] Start got error, see C:\Users\a\logs\master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
` 以下错误

**Comment by super963883929** [comment]
请问这是什么原因?以前的旧版本是没有问题的

**Comment by super963883929** [comment]
![image](https://github.com/QiuYaohong/kuwoMusicApi/assets/73236105/ad6ca1d4-0c20-4dc8-9db8-bb41bfa2d600)
这东西好像都没有

**Comment by qyhqiu** [comment]
你的设备是mac 还是win呀 ，我的win，没有这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: super963883929 ***@***.***&gt;
发送时间: 2023年7月22日 15:52
收件人: QiuYaohong/kuwoMusicApi ***@***.***&gt;
抄送: qyhqiu ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [QiuYaohong/kuwoMusicApi] 关于日志文件无法自动删除问题 (Issue #16)





 

 这东西好像都没有

**Comment by qyhqiu** [comment]
是找不到文件嘛，你可以单独copy出来到这个文件里面试下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: super963883929 ***@***.***&gt;
发送时间: 2023年7月22日 15:52
收件人: QiuYaohong/kuwoMusicApi ***@***.***&gt;
抄送: qyhqiu ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [QiuYaohong/kuwoMusicApi] 关于日志文件无法自动删除问题 (Issue #16)





 

 这东西好像都没有

**Comment by super963883929** [comment]
win,能否加下你的QQ或者微信呢?方便联系

**Comment by super963883929** [comment]
![image](https://github.com/QiuYaohong/kuwoMusicApi/assets/73236105/06e75726-d1c2-462d-9e8b-7aca8492054e)我看你这github和git clone 下来的代码上面也没有上传"utils/secret",应该就是这里的问题所在了吗

**Comment by qyhqiu** [comment]
我靠 应该是的 等我晚点回去看看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: super963883929 ***@***.***&gt;
发送时间: 2023年7月22日 16:20
收件人: QiuYaohong/kuwoMusicApi ***@***.***&gt;
抄送: qyhqiu ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [QiuYaohong/kuwoMusicApi] 关于日志文件无法自动删除问题 (Issue #16)





 
我看你这github和git clone 下来的代码上面也没有上传"utils/secret",应该就是这里的问题所在了吗

**Comment by super963883929** [comment]
嗯好,辛苦了

**Comment by qyhqiu** [comment]
> ![image](https://user-images.githubusercontent.com/73236105/255319588-06e75726-d1c2-462d-9e8b-7aca8492054e.png)我看你这github和git clone 下来的代码上面也没有上传"utils/secret",应该就是这里的问题所在了吗

文件提交了， 拉下代码 重新 npm run dev 跑起来看看

**Comment by 13627491210** [comment]
大佬，播放付费接口怎么弄
<img width="934" alt="image" src="https://github.com/QiuYaohong/kuwoMusicApi/assets/37203543/eeed91e1-a6ab-40d7-a04c-de4a33b17b7a">

**Comment by qyhqiu** [comment]
> 大佬，播放付费接口怎么弄 <img alt="image" width="934" src="https://user-images.githubusercontent.com/37203543/255393602-eeed91e1-a6ab-40d7-a04c-de4a33b17b7a.png">

付费音乐 祭了， 不知道怎么弄

**Comment by super963883929** [comment]
可能得去破解APP咯

**Comment by super963883929** [comment]
又改了了,又非法请求了,这kuwo怎么天天改的??

**Comment by UPman24** [comment]
> > 大佬，播放付费接口怎么弄 <img alt="image" width="934" src="https://user-images.githubusercontent.com/37203543/255393602-eeed91e1-a6ab-40d7-a04c-de4a33b17b7a.png">
> 
> 付费音乐 祭了， 不知道怎么弄

[【这是文件点击下载】zy-kuwo.zip](https://github.com/QiuYaohong/kuwoMusicApi/files/12072199/zy-kuwo.zip)

## 参考 #19 

## 1.先运行 nodejs

```npm install```

```npm run dev```

## 2.运行python

### (1)直接运行

```pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple```

```python MainServer.py```

### (2)docker运行

```docker build -t kuwopy .```

```docker build -t kuwopy .```

```docker run -p 8899:8899 -it kuwopy```

**Comment by UPman24** [comment]
@QiuYaohong 但是遇到新问题，酷我头好像更新了，原先的又没用了

**Comment by AffectionParadise** [comment]
这几天又在频繁更新，有时一天改多少次
